# yaml-language-server: $schema=https://json.schemastore.org/ansible-playbook.json
- name: Build the topology
  hosts: localhost
  gather_facts: no
  tags:
    - cml
    - network
  tasks:
    - name: Check for the lab file
      stat:
        path: "{{ cml_lab_file }}"
      register: stat_result
      delegate_to: localhost
      run_once: yes

    - assert:
        that:
          - stat_result.stat.exists
          - cml_host != ""
          - cml_username != ""
          - cml_password != ""
          - cml_lab != ""
        msg: "CML host, credentials, and topology file are required.  Verify the requirements in README are met."
      delegate_to: localhost
      run_once: yes

    - name: Create the lab
      cisco.cml.cml_lab:
        host: "{{ cml_host }}"
        user: "{{ cml_username }}"
        password: "{{ cml_password }}"
        lab: "{{ cml_lab }}"
        state: present
        file: "{{ cml_lab_file }}"
      register: results

    - name: Refresh Inventory
      meta: refresh_inventory    

- name: Start unmanaged nodes
  hosts: external_connector:unmanaged_switch
  connection: local
  gather_facts: no
  tags:
    - start
    - network
  tasks:
    - name: Start the infrastructure nodes
      cisco.cml.cml_node:
        name: "{{ inventory_hostname }}"
        host: "{{ cml_host }}"
        user: "{{ cml_username }}"
        password: "{{ cml_password }}"
        lab: "{{ cml_lab }}"
        state: started
      delegate_to: localhost

- name: Start the network
  hosts: cml_hosts:!external_connector:!unmanaged_switch
  connection: local
  gather_facts: no
  tags:
    - start
    - network
  vars:
    config_root: "{{ lookup('env', 'PWD') }}/files"
    cml_config_file: "{{ config_root }}/{{ cml_config }}"
  tasks:
    - name: Read config file
      set_fact:
        day0_config: "{{ lookup('template', cml_config ) }}"
      when: cml_config is defined and cml_config

    - name: Start Node
      cisco.cml.cml_node:
        name: "{{ inventory_hostname }}"
        host: "{{ cml_host }}"
        user: "{{ cml_username }}"
        password: "{{ cml_password }}"
        lab: "{{ cml_lab }}"
        state: started
        image_definition: "{{ cml_image_definition | default(omit) }}"
        config: "{{ day0_config | default(omit) }}"
      delegate_to: localhost
