- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - name: Stop the lab
      cisco.cml.cml_lab:
        host: "{{ cml_host }}"
        user: "{{ cml_username }}"
        password: "{{ cml_password }}"
        lab: "{{ cml_lab }}"
        state: stopped
      tags:
        - stop
        - wipe
        - erase
    - name: Wipe the lab
      cisco.cml.cml_lab:
        host: "{{ cml_host }}"
        user: "{{ cml_username }}"
        password: "{{ cml_password }}"
        lab: "{{ cml_lab }}"
        state: wiped
      tags:
        - wipe
        - erase
    - name: Erase the lab
      cisco.cml.cml_lab:
        host: "{{ cml_host }}"
        user: "{{ cml_username }}"
        password: "{{ cml_password }}"
        lab: "{{ cml_lab }}"
        state: absent
      tags:
        - erase
